/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMigrationManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "isEligibleForMigration" | "migrateToDex"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isEligibleForMigration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "migrateToDex",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isEligibleForMigration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateToDex",
    data: BytesLike
  ): Result;
}

export interface IMigrationManager extends BaseContract {
  connect(runner?: ContractRunner | null): IMigrationManager;
  waitForDeployment(): Promise<this>;

  interface: IMigrationManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isEligibleForMigration: TypedContractMethod<
    [tokenAddress: AddressLike],
    [boolean],
    "view"
  >;

  migrateToDex: TypedContractMethod<
    [tokenAddress: AddressLike],
    [string],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isEligibleForMigration"
  ): TypedContractMethod<[tokenAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "migrateToDex"
  ): TypedContractMethod<[tokenAddress: AddressLike], [string], "payable">;

  filters: {};
}
