/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMigrationManager,
  IMigrationManagerInterface,
} from "../../../contracts/MigrationManager.sol/IMigrationManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "isEligibleForMigration",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "migrateToDex",
    outputs: [
      {
        internalType: "address",
        name: "poolAddress",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IMigrationManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMigrationManagerInterface {
    return new Interface(_abi) as IMigrationManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMigrationManager {
    return new Contract(address, _abi, runner) as unknown as IMigrationManager;
  }
}
