"use client";

import React, { useState } from "react";
import { ChevronDown } from "lucide-react";

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: "What is an Attention Market?",
      answer: "An Attention Market on KarmaFi lets you trade 'Karma' shares linked to a specific social media post (like a Reddit thread). If you believe the post will go viral, you buy shares early. As more people discover the post and buy in, the share price increases.",
    },
    {
      question: "Do I have to pay gas fees to launch a market?",
      answer: "No. KarmaFi subsidizes the gas fees for Curators launching new markets. You can spot a trending post on Reddit and launch a market for it instantly, paying 0 gas fees on the BNB Chain.",
    },
    {
      question: "How does the Creator Claim Vault work?",
      answer: "If someone launches a market based on your Reddit post, 30% of all trading fees generated by that market are sent to a Creator Claim Vault. You can verify your Reddit account to claim the funds in that vault permanently.",
    },
    {
      question: "What happens if a post is deleted?",
      answer: "If the underlying social media post is deleted or removed by moderators, the market is automatically frozen. Liquidity providers can withdraw their funds, and traders can redeem their shares at the final frozen price.",
    },
  ];

  return (
    <section id="faq" className="w-full py-12 bg-[#FFFAF5]">
      <div className="mx-auto max-w-[700px] px-6">
        
        <div className="mb-10 text-center">
          <h2 className="text-[28px] md:text-[36px] font-[900] tracking-tight text-[#161616] mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-[16px] text-[#5F5B57] font-medium">
            Everything you need to know about trading attention.
          </p>
        </div>

        <div className="flex flex-col gap-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div 
                key={index} 
                className={`overflow-hidden rounded-[20px] border bg-white transition-all duration-200 ${
                  isOpen ? "border-[#FF6B1A] shadow-[0_8px_24px_rgba(255,107,26,0.12)]" : "border-[#F2D8C8] shadow-sm hover:border-[#FF6B1A]"
                }`}
              >
                <button
                  className="flex w-full items-center justify-between p-5 text-left"
                  onClick={() => setOpenIndex(isOpen ? null : index)}
                >
                  <span className="text-[16px] font-extrabold text-[#161616]">
                    {faq.question}
                  </span>
                  <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition-transform duration-200 ${
                    isOpen ? "bg-[#FFF1ED] text-[#FF6B1A] rotate-180" : "bg-[#FFFAF5] text-[#8A817A]"
                  }`}>
                    <ChevronDown className="h-5 w-5" />
                  </div>
                </button>
                
                <div 
                  className={`grid transition-all duration-300 ease-in-out ${
                    isOpen ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"
                  }`}
                >
                  <div className="overflow-hidden">
                    <p className="px-5 pb-5 pt-0 text-[14.5px] font-medium leading-relaxed text-[#5F5B57]">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
