import React from "react";
import { Search, Plus, TrendingUp, HandCoins } from "lucide-react";

export default function HowItWorks() {
  const steps = [
    {
      title: "Discover & Paste",
      description: "Spot a Reddit post starting to gain traction before the crowd notices. Paste the URL into KarmaFi.",
      icon: Search,
    },
    {
      title: "Launch a Market",
      description: "Pay 0 gas on BNB Chain to instantly launch a live Attention Market around that specific post.",
      icon: Plus,
    },
    {
      title: "Trade the Signal",
      description: "Buy Karma shares if you think the post will go viral, or sell if you think the momentum is dying.",
      icon: TrendingUp,
    },
    {
      title: "Creators Claim",
      description: "The original Reddit creator can claim a permanent 30% share of all fees generated by the market.",
      icon: HandCoins,
    }
  ];

  return (
    <section className="w-full py-12 bg-[#FFFDFB] border-b border-[#F2D8C8]">
      <div className="mx-auto max-w-[1080px] px-6">
        
        <div className="mb-12 text-center">
          <h2 className="text-[28px] md:text-[36px] font-[900] tracking-tight text-[#161616] mb-3">
            How KarmaFi Works
          </h2>
          <p className="mx-auto max-w-2xl text-[16px] text-[#5F5B57] font-medium">
            Turn social signals into liquid markets in seconds.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
          {steps.map((step, index) => {
            const Icon = step.icon;
            return (
              <div 
                key={index} 
                className="relative flex flex-col items-start rounded-[24px] border border-[#F2D8C8] bg-white p-6 shadow-sm transition-shadow hover:shadow-[0_16px_40px_rgba(255,107,26,0.1)]"
              >
                <div className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-[#FFF1ED] text-[#FF6B1A]">
                  <Icon className="h-5 w-5" />
                </div>
                
                {/* Step Number Background */}
                <div className="absolute top-5 right-5 text-5xl font-black text-[#FFF1ED] pointer-events-none">
                  {index + 1}
                </div>

                <h3 className="mb-2 text-[16px] font-extrabold text-[#161616] z-10">{step.title}</h3>
                <p className="text-[14.5px] font-medium text-[#5F5B57] leading-relaxed z-10">
                  {step.description}
                </p>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
