/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeDistributor,
  IFeeDistributorInterface,
} from "../../../contracts/BondingCurveMarket.sol/IFeeDistributor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sourceHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "curator",
        type: "address",
      },
    ],
    name: "distributeFees",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IFeeDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeDistributorInterface {
    return new Interface(_abi) as IFeeDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeDistributor {
    return new Contract(address, _abi, runner) as unknown as IFeeDistributor;
  }
}
