/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICreatorClaimVault,
  ICreatorClaimVaultInterface,
} from "../../../contracts/FeeDistributor.sol/ICreatorClaimVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sourceHash",
        type: "bytes32",
      },
    ],
    name: "depositCreatorRewards",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ICreatorClaimVault__factory {
  static readonly abi = _abi;
  static createInterface(): ICreatorClaimVaultInterface {
    return new Interface(_abi) as ICreatorClaimVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICreatorClaimVault {
    return new Contract(address, _abi, runner) as unknown as ICreatorClaimVault;
  }
}
